# write a github action's workflow to run e2e test on every push
name: e2e test

on: [push]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: âš™ï¸ Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        
      - name: ðŸ“¥ Install dependencies
        run: pnpm install


      - name: ðŸ“¥ Install e2e dependencies
        run: pnpm install -g concurrently wait-on

      - name: ðŸ“¥ playwright install
        run: pnpm --filter e2e exec playwright install --with-deps

      - name: ðŸš€ Run e2e pre scripts
        shell: bash
        run: pnpm e2e:pre

      - name: ðŸš€ Run e2e test
        shell: bash
        run: >
          concurrently -n "bg,e2e"
          -c "green,bgBlue.bold"
          -s "last" --kill-others
          "pnpm e2e:bg"
          "sleep 6 && e2e:run"

      - name: ðŸ“¤ Upload e2e report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-report
          path: pkgs/e2e/playwright-report/
          retention-days: 20
